### ISSUE TITLE
Please delete your junk

### ISSUE THREAD

**Issue by moonlightz** [acidvegas/efknockr#2]
I don't know who you are and why you created this pitful spamming junk.
Your work is plaguing micro, small, medium, and big networks including mine.
Unfortunately for you, your junk no longer works against my network.
Aside that, your spam is spooking users from the networks already frustrated by the coming of social networks and spambots.
Don't you have nothing better to do?
It's not a matter of proof-of-concept, it's plain madness and evilness. It ended in wrong hands and we are all paying for it.
This is just a warning. IF I see them keeping coming the networks I am in, I will ask the Github support team to delete this repository and all other siminar things. IF you want to test, test using YOUR NETWORK.
Are we understood?

**Comment by acidvegas** [comment]
Yeah maybe you should read over the Github terms of service **little guy**.

Github has CVE's and 0days, & botnet source codes all over it's platform, shared as a "proof of concept" so that network operators & researchers can analyze how these things work in an effort to better understand them and mitigate the problems. You are ALLOWED to share content like this on Githubs platform, so as long as you include a disclaimer in the README...which I have included. Just so you can save yourself the time... have a look at [this](https://github.com/jgamblin/Mirai-Source-Code). Ever wonder why this never got taken down?

# So no, I do not think we are on the same page here.

Closing this because you are just rambling and not being productive at all on this matter.
